TehShrike/deepmerge

index.js
test/merge.js

So, I found that the typeof null is an object. So, when null exists in an array it wants to attempt a merge on it. Well, then Object.keys(null) bombs out. This resolves the issue :smile:

Resolve an issue when null is in an array

---

index.js

- replacing bool && val || val with the more readable ternary operator
- turned an else block that contained only an if block into an else if

Small refactors for clarity

---

README.markdown
index.js
test/custom-array-merge.js

A potential fix for #14, #20, #21, #22, #24, #32.
The default merge strategy is exactly the same as it was before (though I'm suspicious of that falsey target property check on line 41 - that can be dealt with as a separate issue if need be).
You can implement whatever other array-merging strategy you like - the merge function is passed both arrays, plus the original options passed to `deepmerge`.
Any thoughts?  Is this a good general solution?  I didn't want to add complexity while solving this common issue.
I did a bit of refactoring in the first commit of this pull request, mostly to get rid of abbreviated variable names.

Custom array merging

---

test/merge.js

Hello! Currently in the process of moving away from lodash, looking to use this library for deep merging.
Currently, if you merge `{ array: [] }` and `{ array: undefined }`, you get `{ array: null }`. This seems… odd.
My preferred behaviour would be for the result to be `{ array: [] }` - this is how `lodash/merge` behaves - but at the very least it should probably by `{ array: undefined }`.
Thoughts? Happy to add a fix to this PR, whatever is decided.

Added tests case for {a:[]} {a:undefined}

---

index.js
test/merge.js

Fixes a crash in the current version.  Would be published as a patch release.
There's a merge conflict on #36, so I grabbed @macdja38's test and added the post-#37-fix.
Look reasonable to everyone?

Merge arrays onto objects

---

README.markdown
index.js
test/merge.js

Added option `clone` as boolean to clone objects before merge. Fixes #28 issue.

Add option to clone objects before merge. Fixes #28 issue.

---

.gitignore
.npmignore

Just a bit of maintenance.  Main thing of note is that this would keep the tests from being published to npm, saving 10K or so.

Updating ignore files

---

index.js
test/merge.js

- Refactored
```js
if (clone && isMergeableObject(e)) {
e = deepmerge(emptyTarget(e), e)
}
```
into a `cloneIfNecessary` function.
- Added a test for the shallow array copy issue noted over at https://github.com/KyleAMathews/deepmerge/pull/44#issuecomment-253238515
- Fixed the shallow array copy
This also fixes a bug where the `deepmerge` clone calls weren't being passed the `clone` option (or any other options).

Small refactor + bug fix

---

index.js
test/merge-all.js

Hi!
As we discussed [here](https://github.com/KyleAMathews/deepmerge/issues/33#issuecomment-258039194), I've made a test file with tests for calling.
It doesn't test any functionality, because actually it depends on implementation.
So, the first object in array is the target, and all others are sources? And all tests for functionality should be the same as in the file `test/merge.js`? I can add them as well, just want to ensure.
Hope it is what you've meant =)
cc @TehShrike

merge.all tests and implementation

---

README.markdown

- Clarify `arrayMerge`'s arguments.
- Fix `clone` heading level.

Improve options section of the readme

---

README.markdown

I tend to look for these metrics when evaluating packages, this makes it readily available.  ¯\\\_(ツ)_/¯
```sh
$ npm install uglify-js
$ ./node_modules/.bin/uglifyjs --compress --mangle -- index.js | wc -c
1076
$ ./node_modules/.bin/uglifyjs --compress --mangle -- index.js | gzip -c | wc -c
533
```

README: add info about source code file size

---

.gitignore
README.markdown
index.js
package-lock.json
package.json
rollup.config.js
test/merge.js

Fixes #58
Drops the hardcoded UMD pattern, allowing bundlers to avoid grabbing it.
Moves the isMergeableObject function out to its own module, allowing other libraries to use the same algorithm for iterating over objects (see #61).
Also fixed some test jank by removing unused variables and adding a missing `var`

Publish ESM + CJS + UMD modules

---

index.js
test/merge.js

This fix made a lot of sense, since we already had a test case and a logic flow specifically handling the "array onto object" case.
That makes me feel a bit better about releasing this as a patch version. though I may still do a feature version bump for paranoia's sake, since it is a decent behavioral change.
Fixes #65

Stop objects from being merged onto arrays

---

readme.md

Fix the oldArrayMerge example

---

readme.md

Hey @KyleAMathews, I took a stab at minor improvements to the readme. Please feel free to reject these if you don't like them.

Minor adjustments to readme

---

readme.md

- standardize on hashes for all headers
- change the headers containing code to be formatted as code

Some markdown header tweaks

---

index.d.ts
package-lock.json
package.json
test/typescript.ts

This PR adds working TypeScript definitions (the [DefinitelyTyped ones](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/deepmerge/index.d.ts) don't work). JavaScript projects can take two approaches to providing TS definitions:
* provide them with the npm package
* provide them in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/)
The second approach is [recommended](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) by the TypeScript project. For projects that are willing to take on the maintenance of typedefs the first approach seems preferable to me. For projects that would rather focus strictly on JS and let the TS community handle typedefs, the second is clearly preferable.
@TehShrike [indicated …

Add TypeScript definitions and test

---

index.d.ts
test/typescript.ts

fixes issue #120 
remove default export

fix type definition

---

changelog.md
package.json
readme.md
rollup.config.js

As a workaround for all the Webpack users
Fixes #123
Fixes #87
Fixes #97

Remove ES module build

---

index.d.ts
test/typescript.ts

Hey,
Thank you for this great library, I just happened to have a case where `deepmerge.all` came in handy and I wanted to have the types set up right, so this is why I would need this change.

Add generic type overwrite to deepmerge.all

---

.travis.yml

v6 ended in April 2019.
v8 will end soon on June 1, 2019.
https://github.com/nodejs/Release

Drop Node v6 and v11, add Node v12

---

package-lock.json
package.json
readme.md
rollup.config.js
test/custom-array-merge.js
test/custom-is-mergeable-object.js
test/merge-all.js
test/merge.js

gotta make those npm audit warnings go away
updating tap brought in an annoying postinstall script via core-js, so I switched to tape
updating rollup brought in a dependency on @types/node that caused the typescript test to break, so I added an explicit dependency on @types/node v8.x.x to correct for it.

Bump dependencies, switch from tap to tape

---

package-lock.json
package.json
rollup.config.js

UMD bundle has quite big wrapper which increases users bundle size.
Though webpack both umd and cjs wraps with own module, rollup may
optimize commonjs version
I built the following entry point with both cjs and umd
```js
import deepmerge from './dist/{umd,cjs}.js';
console.log(deepmerge)
```
Here's the result of minified bundles
```js
cjs.js: 1305
umd.js: 1557
```
Here's their not minified content
<details>
<summary>umd</summary>
```js
var commonjsGlobal = typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};
function createCommonjsModule(fn, module) {
return module = { exports: {} }, fn(module, module.exports), module.exports;
}
var umd = createCommonjsModule(function …
```

Provide commonjs entry point instead umd

---

index.js
test/custom-array-merge.js

- Custom arrayMerge implementations can call options.cloneUnlessOtherwiseSpecified to use
the default clone function
#85

Expose cloneUnlessOtherwiseSpecified to array merge function

---

index.js
test/merge.js

fixes #166 
Uses `Object.assign()` when setting default options, to avoid mutating passed-in options object. 
Adds test to ensure options object isn't mutated.

Stops mutating options object

---

index.js
test/prototype-poisoning.js

- When the src object has an own __proto__ property, avoid
modifying the result object's prototype

Copy own __proto__ safely

---

changelog.md
index.js
readme.md
test/merge.js

Allow falsey values to be merged

---

readme.md

One example was using spaces for indentation.  Noticed by @midnightcodr and reported in #174

Fix inconsistent indentation

---

changelog.md
index.js
test/merge.js

#167 (Stops mutating options object) was reverted due to #171 (IE 11 regression).
I re-implemented the functionality without using Object.assign.

Avoid mutating options

---

changelog.md
index.js
readme.md
test/merge.js

Fixes #208
Potentially fixes #186
Fixes #163
Potentially fixes #212

Un-deprecate clone, make it not a liar about the root object

---

index.js

This changeset prevents `getEnumerableOwnPropertySymbols()` from throwing when `target.propertyIsEnumerable` is undefined. It follows the same convention of `Object.propertyIsEnumerable.call(target, key)` that is used a few lines below.

Prevent getEnumerableOwnPropertySymbols from throwing when target.propertyIsEnumerable is undefined

---

readme.md

According to [this](https://github.com/jonschlinkert/is-plain-object#usage).

Fix isPlainObject require syntax in isMergeableObject example from readme.md
